### ISSUE TITLE
Transacciones rechazadas al pasar a DEBUG = False

### ISSUE THREAD

**Issue by ycanales** [Nomadblue/django-chile-payments#5]
Hola!

Me ocurre que al pasar la configuración de django a `DEBUG = False` me rechaza las transacciones.
Con `DEBUG = True` no hay problema en realizar transacciones de prueba.
El LogEntry no da mucha luz sobre qué puede ser, un extracto:

```
;Inicio de filtrado
;Archivo parseado
;Datos Filtrados con exito
;Parseo realizado
;Datos en datos/tbk_config.dat
;Mac generado
;Construccion TBK_PARAM
;TBK_PARAM encriptado
;Datos listos para ser enviados
;Medio 1: Transaccion segura
;Datos validados
;Token=e87a7b2317443fedb4365f22eb540225fd8cb4f87df0bb777a892adbb8d54641
;Redireccion web
;Todo OK
```
Comparado al log de una transacción exitosa la que sigue con la operación `check_mac`.

Cualquier sugerencia les agradezco.
Saludos!

**Comment by ividela** [comment]
Qué versión de Django usas? y de Python?

**Comment by ycanales** [comment]
Django 1.7.1, python 2.7.6

**Comment by ycanales** [comment]
El problema era debido a un código malo de la aplicación presente en un `signal`.
Con `DEBUG = True` al parecer la respuesta (el traceback) era interpretado como una respuesta afirmativa por webpay y por eso aún así aprobaba las transacciones.

Gracias por el interés!
